apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ysyc69kdb-go 
  janus-idp.io/tekton: ysyc69kdb-go
  backstage.io/kubernetes-id: ysyc69kdb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ysyc69kdb-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  