apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ysyc69kdb-go-gitops
  description: This is GitOps manifest for ysyc69kdb-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ysyc69kdb-go
    backstage.io/kubernetes-id: ysyc69kdb-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ysyc69kdb-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ysyc69kdb-go
